### ISSUE TITLE
Dleft: initial feeder and feeder

### ISSUE THREAD

**Issue by therese3** [yakir12/MAT2db.jl#42]
When going through Displacement left, I realized that the following symbols should be changed: 

- feeder/pick up => initial feeder
- drop off => feeder

**Comment by yakir12** [comment]
I  personally believe that we should always use `pickup` and `dropoff` instead of *anything* else. These terms are better because they are much more general and do not restrict us to experiments where the animal was transported on a feeder (consider Ayse's experiments and ones where the animal was transported on cardboard/sand paper etc). So if it was up to me we would only use these more general terms, `pickup` and `dropoff`.

**Comment by yakir12** [comment]
@therese3, do you agree? If so, let's close this then.
